/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipc1.proyecto2;

/**
 *
 * @author Moreira Paz
 */
public class ModificarUsu extends javax.swing.JFrame {

    /**
     * Creates new form ModificarUsu
     */
    public ModificarUsu() {
        initComponents();
        
        Usuario actuales = Registro.LCU.buscar(Login.Nameusu);
    
        lblname.setText(actuales.nombre);
        lblusu.setText(actuales.nusuario);
        lblmail.setText(actuales.correo);
        lbltargeta.setText("No."+actuales.Targeta);
        lblpass.setText(actuales.contraseña);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmod = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtusu = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txttargeta = new javax.swing.JTextField();
        modname = new javax.swing.JButton();
        modusu = new javax.swing.JButton();
        modtargeta = new javax.swing.JButton();
        modmail = new javax.swing.JButton();
        modpass = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblusu = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblmail = new javax.swing.JLabel();
        lbltargeta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MODIFICAR USUARIO:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Correo Electronico:");

        jLabel6.setText("Targeta de credito:");

        modname.setText("Modificar");
        modname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modnameMouseClicked(evt);
            }
        });

        modusu.setText("Modificar");
        modusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modusuMouseClicked(evt);
            }
        });

        modtargeta.setText("Modificar");
        modtargeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modtargetaMouseClicked(evt);
            }
        });

        modmail.setText("Modificar");
        modmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modmailMouseClicked(evt);
            }
        });

        modpass.setText("Modificar");
        modpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modpassMouseClicked(evt);
            }
        });

        jLabel7.setText("Datos Actuales:");

        lblname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblname.setText("jLabel8");

        lblusu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblusu.setText("jLabel9");

        lblpass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblpass.setText("jLabel10");

        lblmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblmail.setText("jLabel11");

        lbltargeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbltargeta.setText("jLabel12");

        javax.swing.GroupLayout panelmodLayout = new javax.swing.GroupLayout(panelmod);
        panelmod.setLayout(panelmodLayout);
        panelmodLayout.setHorizontalGroup(
            panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmodLayout.createSequentialGroup()
                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelmodLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelmodLayout.createSequentialGroup()
                                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpass)
                                    .addComponent(txtmail)
                                    .addComponent(txttargeta, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(txtusu)))
                            .addGroup(panelmodLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelmodLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addGap(37, 37, 37)
                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(modusu)
                    .addComponent(modpass)
                    .addComponent(modmail)
                    .addComponent(modtargeta)
                    .addComponent(modname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(lblname, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblusu, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblpass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltargeta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
        );
        panelmodLayout.setVerticalGroup(
            panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmodLayout.createSequentialGroup()
                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelmodLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmodLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1)))
                    .addGroup(panelmodLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modname)
                        .addComponent(lblname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modusu)
                    .addComponent(lblusu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modpass)
                    .addComponent(lblpass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modmail)
                    .addComponent(lblmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttargeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modtargeta)
                    .addComponent(lbltargeta))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelmod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       UsuarioInterface Ui = new UsuarioInterface();
       Ui.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void modnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modnameMouseClicked
        Usuario modificacion = Registro.LCU.buscar(Login.Nameusu);
        modificacion.nombre = txtname.getText();
        txtname.setText("");
        
        lblname.setText(modificacion.nombre);
    }//GEN-LAST:event_modnameMouseClicked

    private void modusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modusuMouseClicked
        Usuario modificacion = Registro.LCU.buscar(Login.Nameusu);
        modificacion.nusuario = txtusu.getText();
        Login.Nameusu = modificacion.nusuario;
        txtusu.setText("");
        
        lblusu.setText(modificacion.nusuario);
    }//GEN-LAST:event_modusuMouseClicked

    private void modpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modpassMouseClicked
        Usuario modificacion = Registro.LCU.buscar(Login.Nameusu);
        modificacion.contraseña = txtpass.getText();
        txtpass.setText("");
        
        lblpass.setText(modificacion.contraseña);
    }//GEN-LAST:event_modpassMouseClicked

    private void modmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modmailMouseClicked
        Usuario modificacion = Registro.LCU.buscar(Login.Nameusu);
        modificacion.correo = txtmail.getText();
        txtmail.setText("");
        
        lblmail.setText(modificacion.correo);
    }//GEN-LAST:event_modmailMouseClicked

    private void modtargetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modtargetaMouseClicked
        Usuario modificacion = Registro.LCU.buscar(Login.Nameusu);
        modificacion.Targeta = Integer.parseInt(txttargeta.getText());
        txttargeta.setText("");
     
        lbltargeta.setText("No."+modificacion.Targeta);
    }//GEN-LAST:event_modtargetaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lbltargeta;
    private javax.swing.JLabel lblusu;
    private javax.swing.JButton modmail;
    private javax.swing.JButton modname;
    private javax.swing.JButton modpass;
    private javax.swing.JButton modtargeta;
    private javax.swing.JButton modusu;
    private javax.swing.JPanel panelmod;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txttargeta;
    private javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
