/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipc1.proyecto2;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moreira Paz
 */
public class VerUsuarios extends javax.swing.JFrame {

    DefaultTableModel modelo;
    
    public VerUsuarios() {
        initComponents();
        modelo=new DefaultTableModel();
        modelo.addColumn("Producto");
        this.tablaUsu.setModel(modelo);
        
        NodoUsuario aux = Registro.LCU.inicio;
        
        for (int i = 0; i < Registro.LCU.size; i++) {
            modelo.addRow(new Object[]{aux.usuario.nusuario});
            aux = aux.siguiente;
        }
        
        lblnombre.setText("");
        lblcorreo.setText("");
        lblusu.setText("");
        lbltarjeta.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        regre = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsu = new javax.swing.JTable();
        btndetalle = new javax.swing.JButton();
        lblnombre = new javax.swing.JLabel();
        lblusu = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        lbltarjeta = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USUARIOS:");

        regre.setText("Regresar");
        regre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regreMouseClicked(evt);
            }
        });

        tablaUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaUsu);

        btndetalle.setText("Detalle");
        btndetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndetalleMouseClicked(evt);
            }
        });

        lblnombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblnombre.setText("jLabel2");

        lblusu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblusu.setText("jLabel3");

        lblcorreo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblcorreo.setText("jLabel2");

        lbltarjeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbltarjeta.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regre)
                        .addGap(33, 33, 33)
                        .addComponent(btndetalle)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblusu)
                            .addComponent(lblnombre)
                            .addComponent(lblcorreo)
                            .addComponent(lbltarjeta))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regre)
                    .addComponent(btndetalle)
                    .addComponent(lblnombre))
                .addGap(1, 1, 1)
                .addComponent(lblcorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltarjeta)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndetalleMouseClicked
         int fila = tablaUsu.getSelectedRow();
        String nombre = modelo.getValueAt(fila, 0).toString();
        
        Usuario detalle = Registro.LCU.buscar(nombre);
        
        lblnombre.setText("Nombre: "+detalle.nombre);
        lblcorreo.setText("Correo: "+detalle.correo);
        lblusu.setText("Nombre de Usuario: "+detalle.nusuario);
        lbltarjeta.setText("No. Tarjeta: "+detalle.Targeta);
        
    }//GEN-LAST:event_btndetalleMouseClicked

    private void regreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regreMouseClicked
        Admin a = new Admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_regreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndetalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltarjeta;
    private javax.swing.JLabel lblusu;
    private javax.swing.JButton regre;
    private javax.swing.JTable tablaUsu;
    // End of variables declaration//GEN-END:variables
}
